namespace SPSA.Autorizadores.Aplicacion.DTO
{
	public enum EstadoMonitor
	{
		CIERRE_REALIZADO = 1,
		PENDIENTE_VALIDACION_CIERRE = 2,
		NO_SE_HA_REALIZADO_CIERRE = 3,
		SI = 4,
		NO = 5
	}

	public enum TipoMonitor
	{
		CIERRE_FIN_DIA = 1,
		CAJA_DEFECTUOSA = 2
	}

	public enum ColorSemaforo
	{
		VERDE = 1,
		NARANJA = 2,
		ROJO = 3
	}

	public enum Proceso
	{
		INTERFACE_CARGA_DESCUENTOS_GASTO = 1,
		INTERFACE_CARGA_REGISTRO_VENTAS = 2,
		INTERFACE_CARGA_DETRACCIONES = 3,
		INTERFACE_LOTES_IBK = 4,
		INTERFACE_GENERA_ARCHIVO_PAPERLESS = 5,
		INTERFACE_GENERA_ARCHIVO_GARANTIA_EXTENDIDA = 6,
		INTERFACE_CARGA_VENTAS_PMM = 7,
		INTERFACE_RENDICION_CUPONES_PAVOS = 8,
		INTERFACE_CARGA_VENTAS_SAP_FICO = 9,
		INTERFACE_CARGA_COMISIONES = 10,
		CONFIRMACION_DESPACHO = 11,
		SERVICIO_TECNICO_ELECTRO = 12,
		INTERFACE_VENTA_CUBOS_BI = 13,
		INTERFACE_RAFAGA_VENTAS = 14,
		INTERFACE_ECOMMERCE = 15,
		INTERFACE_COMISIONES = 17,
		INTERFACE_CARGA_TRX_KARDEX_ELECTRONICO = 19,
		CONFIRMACION_CAJAS_LOCAL = 20,
		INTERFACE_VENTA_BI_ECONOMAX = 21,
		INTERFACE_VENTA_EN_LINEA = 22,
		CONFIRMACION_CASH_IN_AGORA = 23,
		CONFIRMACION_TRX_ERROR = 24,
		ALERTA_TRX_DUPLICADAS_ECOMMERCE = 25,
		INTERFAZ_CONSUMO_COMISION_VALES_TARJETAS = 26,
		INTERFAZ_MONITOR_VENTAS_IC = 27,
		INTERFACE_CARGA_REGISTRO_VENTAS_SIRE = 28,
		INTERFACE_CARGA_REGISTRO_VENTAS_SIRE_BORRAR = 92,
		INTERFACE_CARGA_VENTAS_SAP_FICO_CAMUNDA = 99,
		MONITOR_BCT = 29,
		ACTUALIZACION_ESTADO_CIERRE = 30,
		MONITOR_DIFERENCIA_TRANSACCIONES_MONTOS = 31,
		GENERACION_CODIGO_BARRAS_AUTORIZADOR = 32
	}


}