name: Generar Publicado

on:
  push:
    branches: [main, develop]

jobs:
  setup:
  
    runs-on: windows-latest



    steps:
    - name: Checkout code.
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT_GITHUB_ACTION }}
          
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup Nuget
      uses: Nuget/setup-nuget@v1.0.5

   
    

  build:
    needs: setup
    runs-on: windows-latest
    steps:
      - name: Restore nuget packages
        run: nuget restore Web/SPSA.Autorizadores/SPSA.Autorizadores.sln

      - name: Build
        run: msbuild Web/SPSA.Autorizadores/SPSA.Autorizadores.sln /p:DeployOnBuild=true /p:PublishProfile=PublishProfile.xml

  push:
    needs: build
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Generacion de caperta compilado
          push_options: --force
          commit_user_name: Yovanny Zeballos [GitHub Action]
          commit_user_email: zeballos.yovanny@gmail.com
          commit_author: Yovanny Zeballos
