name: Generar Release

on:
  push:
    branches: [main, develop]

jobs:
  build:
  
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
    - name: Checkout code.
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT_GITHUB_ACTION }}
          
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup Nuget
      uses: Nuget/setup-nuget@v1.0.5

    - name: Restore nuget packages
      run: nuget restore Web/SPSA.Autorizadores/SPSA.Autorizadores.sln

    - name: Build
      run: msbuild Web/SPSA.Autorizadores/SPSA.Autorizadores.sln /p:DeployOnBuild=true /p:PublishProfile=PublishProfile.xml

    - name: Zip Compilado Directory 
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'release.zip'
        path: ./Compilado

    # Building a multiline commit message
    # Adjust to your liking
    - run: echo "Generacion de caperta compilado" >> commitmessage.txt
    - run: echo "" >> commitmessage.txt
    - run: echo "" >> commitmessage.txt
    - run: echo "skip-checks:true" >> commitmessage.txt

    # Create a multiline string to be used by the git-auto-commit Action
    - name: Set commit message
      id: commit_message_step
      run: |
        echo 'commit_message<<EOF' >> $GITHUB_OUTPUT
        cat commitmessage.txt >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT

    - name: Get color
      env:
        SELECTED_COLOR: ${{ steps.commit_message_step.outputs.commit_message }}
      run: echo "The selected color is $SELECTED_COLOR"

    
    - name: Commit and Push Changes
      id: commit
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "[skip ci] Generacion de caperta compilado"
        push_options: --force
        commit_user_name: Yovanny Zeballos [GitHub Action]
        commit_user_email: zeballos.yovanny@gmail.com
        commit_author: Yovanny Zeballos
        
    
